---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>",
  df_print = "kable",
  # fig.path = "man/figures/logo.png",
  fig.path = "man/figures/README-",
  message = FALSE,
  out.width = "100%"
)
```

## Predicting this year's Premier League

This repo uses a simplified version of [David Firth's methodology](https://github.com/DavidFirth/alt3code) to predict the outcome of the Premier League for this season. Here are those predictions:

```{r}
data <- readr::read_csv(file = "projections.csv", show_col_types = FALSE)

data |> 
  reactable::reactable(
    filterable = FALSE, 
    highlight = TRUE, 
    borderless = TRUE, 
    defaultPageSize = 20, 
    columns = list(
      Team = reactable::colDef(
        name = "Team", 
        minWidth = 50, 
        sticky = "left"
        ),
      Played = reactable::colDef(
        name = "Played", 
        minWidth = 50, 
        sticky = "left"
        ),
      Exp_Points = reactable::colDef(
        name = "Expected Points", 
        sticky = "right", 
        filterable = FALSE, 
        format = reactable::colFormat(
          separators = TRUE, 
          digits = 1
          )
        )
      )
    )
```
