on:
  push:
  workflow_dispatch:
  # Run every 12 hours from 1am at 56 minutes past the hour
  schedule: [{cron: '56 1/13 * * *'}]

name: scrape

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Fetch latest data
      run: Rscript script.R

    - uses: stefanzweifel/git-auto-commit-action@v5